version: "3"
name: "mongo-demo"
services:
  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./scripts/:/code
      - "dbdata:/data/db"
      - "dbconfig:/data/configdb"
volumes:
  dbdata:
  dbconfig: